### ISSUE TITLE
Please tag version

### ISSUE THREAD

**Issue by t11n** [tburschka/zf2-doctrine-sql-logger#1]
Hi, we are quite happy to use the doctrine sql logger. In our company we made this logger a dependency of a privately hosted package. As the sql-logger is only available as dev-master version via composer, we are not able to make it a dependency, without setting the minimum stability to dev (see https://groups.google.com/d/msg/composer-dev/_g3ASeIFlrc/M36qai4AC6cJ).

Is there any reason to not make a release? Probably a minor release is sufficient, so composer recognises the version as stable (enough).

For now I forked the project to just tag it. With a version tag of "1.0" the package is considered to be stable by composer.

Can you please set a tag on the current dev-master version?

**Comment by tina-junold** [comment]
Done, hope this helps. Feel free to provide other issues if you found more

**Comment by t11n** [comment]
Cool, thanks :+1:
